[package]
name = "ooxml-tui"
version = "0.1.1"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
ratatui = "0.29.0"
tui-tree-widget = "0.23.0"
tui-textarea = "0.7.0"
zip = "2.1.2"
xml-rs = "0.8.20"
